<?php
// Load environment variables if not already loaded
if (!function_exists('getenv') || empty(getenv('APP_ENV'))) {
    if (file_exists(__DIR__ . '/../.env')) {
        $dotenv = \Dotenv\Dotenv::createImmutable(__DIR__ . '/..');
        $dotenv->load();
    }
}

return array(
    /*
     * Application ID generated by AppStore
     */
    'appId' => getenv('SHOPER_APP_ID') ?: '',

    /*
     * Secret generated by AppStore
     */
    'appSecret' => getenv('SHOPER_APP_SECRET') ?: '',

    /*
     * AppStore Secret generated by AppStore
     */
    'appstoreSecret' => getenv('SHOPER_APPSTORE_SECRET') ?: '',


    'db' => array(
        /*
         * PDO DSN
         */
        'connection' => 'mysql:host=' . (getenv('DB_HOST') ?: '127.0.0.1') . ';dbname=' . (getenv('DB_NAME') ?: 'app'),

        /*
         * PDO Database username
         */
        'user' => getenv('DB_USER') ?: '',

        /*
         * PDO Database password
         */
        'pass' => getenv('DB_PASSWORD') ?: ''
    ),

    /*
     * Enable debug mode or not
     */
    'debug' => getenv('APP_ENV') === 'development',

    /*
     * Path to log file or empty to disable logging
     */
    'logFile' => "logs/application.log",


    /*
     * timezone of the application
     *
     * Value is passed to date_default_timezone_set function
     */
    'timezone' => 'Europe/Warsaw',

    'php' => array(
        /*
         * This determines whether errors should be printed to the screen as
         * part of the output or if they should be hidden from the user
         *
         * Value is passed to ini_set function
         */
        'display_errors' => getenv('DISPLAY_ERRORS') ? 'on' : 'off'
    )
);
